apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service-app
  labels:
    app: admin-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : admin-service-app
  template:
    metadata:
      labels:
        app: admin-service-app
    spec:
      containers:
      - name: user-service-app
        image: mukteeshwar/admin-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 9093

---

kind: Service
apiVersion: v1
metadata:
  name:  admin-service-svc
spec:
  selector:
    app:  admin-service-app
  ports:
  - port:  80
    targetPort:  9093
